### PR TITLE
Fix crash with dof handler on true subdomains

### LINKED ISSUE #966: CellIterator causes a OutOfMemoryError
This only happens if the cellset used for the FieldHandler doesn't contain every cell in the grid.

```julia
using Ferrite

grid = generate_grid(Hexahedron, (3,3,3))

FE = MixedDofHandler(grid)
fe_domain = Set(1:4) # with = Set(1:27) the error doesn't happen
fe_field = Field(:u, Lagrange{3, RefCube, 1}(), 3)
fe_fieldHandler = FieldHandler([fe_field], fe_domain)

add!(FE, fe_fieldHandler)
close!(FE)

begin
    cell = CellCache(FE)

    for i in fe_domain
        reinit!(cell, i)
    end

    println("works")
end

begin
    for cell in CellIterator(FE) # causes OutOfMemoryError

    end
end
```

I'm on Ferrite version 0.3.14

here is my versioninfo()
```
Julia Version 1.10.3
Commit 0b4590a550 (2024-04-30 10:59 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: 16 × AMD Ryzen 7 3700X 8-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-15.0.7 (ORCJIT, znver2)
Threads: 8 default, 0 interactive, 4 GC (on 16 virtual cores)
Environment:
  JULIA_EDITOR = code
  JULIA_NUM_THREADS = 8
```

and here is the Stacktrace

```
LoadError: OutOfMemoryError()
Stacktrace:
  [1] _growend!
    @ .\array.jl:1072 [inlined]
  [2] resize!
    @ .\array.jl:1315 [inlined]
  [3] reinit!(cc::CellCache{Vec{3, Float64}, Grid{3, Hexahedron, Float64}, MixedDofHandler{3, Float64, Grid{3, Hexahedron, Float64}}}, i::Int64)
    @ Ferrite C:\Users\johan\.julia\packages\Ferrite\5Ozov\src\iterators.jl:96
  [4] iterate(ci::CellIterator{CellCache{Vec{3, Float64}, Grid{3, Hexahedron, Float64}, MixedDofHandler{3, Float64, Grid{3, Hexahedron, Float64}}}, UnitRange{Int64}}, state_in::Int64)
    @ Ferrite C:\Users\johan\.julia\packages\Ferrite\5Ozov\src\iterators.jl:176
  [5] top-level scope
    @ c:\Users\johan\dev\capriccio-julia\demos\OutOfMemory.jl:26
  [6] eval
    @ .\boot.jl:385 [inlined]
  [7] include_string(mapexpr::typeof(identity), mod::Module, code::String, filename::String)        
    @ Base .\loading.jl:2076
  [8] include_string(m::Module, txt::String, fname::String)
    @ Base .\loading.jl:2086
  [9] invokelatest(::Any, ::Any, ::Vararg{Any}; kwargs::@Kwargs{})
    @ Base .\essentials.jl:892
 [10] invokelatest(::Any, ::Any, ::Vararg{Any})
    @ Base .\essentials.jl:889
 [11] inlineeval(m::Module, code::String, code_line::Int64, code_column::Int64, file::String; softscope::Bool)
    @ VSCodeServer c:\Users\johan\.vscode\extensions\julialang.language-julia-1.79.2\scripts\packages\VSCodeServer\src\eval.jl:271
 [12] (::VSCodeServer.var"#69#74"{Bool, Bool, Bool, Module, String, Int64, Int64, String, VSCodeServer.ReplRunCodeRequestParams})()
    @ VSCodeServer c:\Users\johan\.vscode\extensions\julialang.language-julia-1.79.2\scripts\packages\VSCodeServer\src\eval.jl:181
 [13] withpath(f::VSCodeServer.var"#69#74"{Bool, Bool, Bool, Module, String, Int64, Int64, String, VSCodeServer.ReplRunCodeRequestParams}, path::String)
    @ VSCodeServer c:\Users\johan\.vscode\extensions\julialang.language-julia-1.79.2\scripts\packages\VSCodeServer\src\repl.jl:276
 [14] (::VSCodeServer.var"#68#73"{Bool, Bool, Bool, Module, String, Int64, Int64, String, VSCodeServer.ReplRunCodeRequestParams})()
    @ VSCodeServer c:\Users\johan\.vscode\extensions\julialang.language-julia-1.79.2\scripts\packages\VSCodeServer\src\eval.jl:179
 [15] hideprompt(f::VSCodeServer.var"#68#73"{Bool, Bool, Bool, Module, String, Int64, Int64, String, VSCodeServer.ReplRunCodeRequestParams})
    @ VSCodeServer c:\Users\johan\.vscode\extensions\julialang.language-julia-1.79.2\scripts\packages\VSCodeServer\src\repl.jl:38
 [16] (::VSCodeServer.var"#67#72"{Bool, Bool, Bool, Module, String, Int64, Int64, String, VSCodeServer.ReplRunCodeRequestParams})()
    @ VSCodeServer c:\Users\johan\.vscode\extensions\julialang.language-julia-1.79.2\scripts\packages\VSCodeServer\src\eval.jl:150
 [17] with_logstate(f::Function, logstate::Any)
    @ Base.CoreLogging .\logging.jl:515
 [18] with_logger
    @ .\logging.jl:627 [inlined]
 [19] (::VSCodeServer.var"#66#71"{VSCodeServer.ReplRunCodeRequestParams})()
    @ VSCodeServer c:\Users\johan\.vscode\extensions\julialang.language-julia-1.79.2\scripts\packages\VSCodeServer\src\eval.jl:263
 [20] #invokelatest#2
    @ .\essentials.jl:892 [inlined]
 [21] invokelatest(::Any)
    @ Base .\essentials.jl:889
 [22] (::VSCodeServer.var"#64#65")()
    @ VSCodeServer c:\Users\johan\.vscode\extensions\julialang.language-julia-1.79.2\scripts\packages\VSCodeServer\src\eval.jl:34
```

### PR DESCRIPTION
**Pull request by termi-official**
Resolves #966 on master.

### CODE REVIEW

File: test/test_mixeddofhandler.jl [hunk 1]
```diff
@@ -643,6 +643,24 @@ function test_vtk_export()
...
+    dh = DofHandler(grid)
+    sdh = SubDofHandler(dh, [1,2,3])
+    add!(sdh, :u, Lagrange{RefHexahedron,1}()^3)
+    close!(dh)
+
+    for cell in CellIterator(sdh)
+    end
+
+    for cell in CellIterator(dh, [1,2,3])
+    end
```
Comment (KnutAM) [inline test/test_mixeddofhandler.jl:658]: These didn't fail before either, right, so perhaps not required? 
Would also be nice to add a link to the issue - I also find that helpful in understanding why something is smoke-tested.

**Review by KnutAM — APPROVED** [review]
LGTM

File: test/test_mixeddofhandler.jl (hunk 1 above)
Comment (termi-official) [reply test/test_mixeddofhandler.jl:658]: This failed on last release, so you can see this as a smoke test to see if things do at least not crash.

Will add the issue later.

File: test/test_mixeddofhandler.jl [hunk 2]
```diff
@@ -643,6 +643,26 @@ function test_vtk_export()
...
 
+function test_celliterator_on_true_subdomain_smoketest()
+    grid = generate_grid(Hexahedron, (3,3,3))
+
+    dh = DofHandler(grid)
+    sdh = SubDofHandler(dh, [1,2,3])
+    add!(sdh, :u, Lagrange{RefHexahedron,1}()^3)
+    close!(dh)
+
+    # The folloging statements just check that the iterator
```
Comment (KnutAM) [inline test/test_mixeddofhandler.jl:654]:
```suggestion
    # The following statements just check that the iterator
```

File: test/test_mixeddofhandler.jl [hunk 3]
```diff
@@ -643,6 +643,26 @@ function test_vtk_export()
     rm(filename*".vtu") # clean up
 end
 
+function test_celliterator_on_true_subdomain_smoketest()
+    grid = generate_grid(Hexahedron, (3,3,3))
```
Comment (KnutAM) [inline test/test_mixeddofhandler.jl:647]:
```suggestion
    grid = generate_grid(Hexahedron, (2,2,2))
```

File: test/test_mixeddofhandler.jl [hunk 4]
```diff
@@ -643,6 +643,26 @@ function test_vtk_export()
...
+    # The folloging statements just check that the iterator
+    # does not crash at least. Regression for #966
+    for cell in CellIterator(sdh)
+    end
+
+    for cell in CellIterator(dh, [1,2,3])
+    end
+
+    for cell in CellIterator(dh)
+    end
```
Comment (KnutAM) [inline test/test_mixeddofhandler.jl:663]:
```suggestion
        if cellid(cell) <= 3
            @test length(celldofs(cell)) == getnbasefunctions(ip)
        else
            @test length(celldofs(cell)) == 0
        end
    end
```

File: test/test_mixeddofhandler.jl [hunk 5]
```diff
@@ -643,6 +643,26 @@ function test_vtk_export()
     rm(filename*".vtu") # clean up
 end
 
+function test_celliterator_on_true_subdomain_smoketest()
+    grid = generate_grid(Hexahedron, (3,3,3))
+
+    dh = DofHandler(grid)
+    sdh = SubDofHandler(dh, [1,2,3])
+    add!(sdh, :u, Lagrange{RefHexahedron,1}()^3)
```
Comment (KnutAM) [inline test/test_mixeddofhandler.jl:651]:
```suggestion
    ip = Lagrange{RefHexahedron,1}()
    add!(sdh, :u, ip)
```

**Review by KnutAM — APPROVED** [review]
Suggestions to test the new behavior, and just reduce the test mesh since more cells and vector interpolations doesn't really test anything more...

File: test/test_mixeddofhandler.jl (hunk 4 above)
Comment (termi-official) [reply test/test_mixeddofhandler.jl:663]: Do we really want to enforce this behavior?

File: test/test_mixeddofhandler.jl (hunk 3 above)
Comment (termi-official) [reply test/test_mixeddofhandler.jl:647]: I am not seeing the issue here, could you explain?

Comment (KnutAM) [reply test/test_mixeddofhandler.jl:647]: Just a general idea that I think we should minimize the workload during tests since they already take long. Of course, this is **very** minor, but a lot of minor things add up...

File: test/test_mixeddofhandler.jl (hunk 4 above)
Comment (KnutAM) [reply test/test_mixeddofhandler.jl:663]: I don't think we should document it, but it is good to be aware if a later change changes this behavior.
