### PR TITLE
AffineConstraints: Fix usage with get_rhs_data.

### LINKED ISSUE #419: apply_rhs! doesn't work with affine constraints
I believe that https://github.com/Ferrite-FEM/Ferrite.jl/blob/9bfc3ad57a9a31728a9853f5f63625da6e43cff2/src/Dofs/ConstraintHandler.jl#L672-L678 needs to be done inside `apply_rhs!`.

### PR DESCRIPTION
**Pull request by fredrikekre**
This applies affine constraints also in apply_rhs! for solving a system
with multiple right hand sides. Also adds tests, and removes the
workarounds for this bug in computational homogenization example.

Fixes #419.

### CODE REVIEW

File: src/Dofs/ConstraintHandler.jl [hunk 1]
```diff
@@ -111,22 +111,31 @@ See also: [`get_rhs_data`](@ref).
...
-        if length(f) != 0
-            vz = applyzero ? zero(eltype(f)) : v
-            f[d] = vz * m
+    end
+    @inbounds for ac in ch.acs
+        global_dof = ac.constrained_dof
+        for (d, v) in ac.entries
+            f[d] += f[global_dof] * v
         end
+        f[global_dof] = 0
```
Comment (lijas) [inline src/Dofs/ConstraintHandler.jl:132]: Here you set it f[global_dof] = 0, but on line 138 you set it to vz*m... can you merge these loops?

Perhaps from line132:
```
vz = applyzero ? zero(eltype(f)) : ac.inhomogenity
f[global_dof] = vz*m
```

and remove the second loop?

Comment (fredrikekre) [reply src/Dofs/ConstraintHandler.jl:132]: Not sure, this loops over the constraints, and the other loop is over all constrained dofs. Would have to do a lookup whether the dof is a affine-constrained dof or not in that case. I think it is pretty fast to iterate through these anyway. (And as it is now it matches the code of `apply!(K, f, ch)`, which does `_condense!` in between.
